### ISSUE TITLE
This tool does not support PACTH,PUT and DELETE request

### ISSUE THREAD

**Issue by zhoudqa** [uuau99999/moco-node#1]
Dear yaho:
In interface RequestContract only define GET and POST type for property method.I hope u can update this tool.

**Comment by uuau99999** [comment]
@zhoudqa  Fixed at [309cfb2](https://github.com/uuau99999/moco-node/commit/309cfb216b9405d8c0dd6827c0d731a8ef7b7343) and release 1.1.6
